-- =============================================================================
-- Snowflake Setup: Database, Schemas, Roles, Warehouse
-- Run as: ACCOUNTADMIN (or role with CREATE DATABASE, CREATE ROLE privileges)
-- =============================================================================

-- =====================
-- 1. DATABASE
-- =====================
CREATE DATABASE IF NOT EXISTS IOT_PIPELINE
    COMMENT = 'IoT Fleet Monitor Pipeline - sensor data from 50 devices';

USE DATABASE IOT_PIPELINE;

-- =====================
-- 2. SCHEMAS
-- =====================
-- RAW: Landing zone for semi-structured JSON data (VARIANT columns)
CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw ingested data from S3 - VARIANT columns, no transformation';

-- STAGING: Parsed and typed columns from raw VARIANT data
CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'Parsed data with typed columns via TRY_CAST';

-- INTERMEDIATE: Deduplication, validation, enrichment
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE
    COMMENT = 'Deduped, validated, enriched data';

-- MARTS: Business-ready tables (Iceberg format for open access)
CREATE SCHEMA IF NOT EXISTS MARTS
    COMMENT = 'Business-ready dimensions and facts - Iceberg tables on S3';

-- MONITORING: Freshness checks, quality logs
CREATE SCHEMA IF NOT EXISTS MONITORING
    COMMENT = 'Pipeline health monitoring and freshness tracking';

-- =====================
-- 3. WAREHOUSE
-- =====================
CREATE WAREHOUSE IF NOT EXISTS IOT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60          -- Suspend after 60 seconds of inactivity
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for IoT pipeline processing';

-- =====================
-- 4. ROLES (RBAC - Least Privilege)
-- =====================

-- IOT_LOADER: Can write to RAW, read from stages
CREATE ROLE IF NOT EXISTS IOT_LOADER
    COMMENT = 'Loads raw data from S3 into RAW schema';

-- IOT_TRANSFORMER: Can read RAW, write to STAGING/INTERMEDIATE/MARTS
CREATE ROLE IF NOT EXISTS IOT_TRANSFORMER
    COMMENT = 'Transforms data through dbt layers';

-- IOT_READER: Read-only on MARTS (for BI tools, analysts)
CREATE ROLE IF NOT EXISTS IOT_READER
    COMMENT = 'Read-only access to mart tables';

-- =====================
-- 5. GRANT PRIVILEGES
-- =====================

-- Warehouse access for all roles
GRANT USAGE ON WAREHOUSE IOT_WH TO ROLE IOT_LOADER;
GRANT USAGE ON WAREHOUSE IOT_WH TO ROLE IOT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE IOT_WH TO ROLE IOT_READER;

-- Database access
GRANT USAGE ON DATABASE IOT_PIPELINE TO ROLE IOT_LOADER;
GRANT USAGE ON DATABASE IOT_PIPELINE TO ROLE IOT_TRANSFORMER;
GRANT USAGE ON DATABASE IOT_PIPELINE TO ROLE IOT_READER;

-- IOT_LOADER: write to RAW only
GRANT USAGE ON SCHEMA RAW TO ROLE IOT_LOADER;
GRANT CREATE TABLE ON SCHEMA RAW TO ROLE IOT_LOADER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA RAW TO ROLE IOT_LOADER;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA RAW TO ROLE IOT_LOADER;

-- IOT_TRANSFORMER: read RAW, write to STAGING/INTERMEDIATE/MARTS
GRANT USAGE ON SCHEMA RAW TO ROLE IOT_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE IOT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE IOT_TRANSFORMER;

GRANT USAGE ON SCHEMA STAGING TO ROLE IOT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA STAGING TO ROLE IOT_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA STAGING TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAGING TO ROLE IOT_TRANSFORMER;

GRANT USAGE ON SCHEMA INTERMEDIATE TO ROLE IOT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA INTERMEDIATE TO ROLE IOT_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA INTERMEDIATE TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA INTERMEDIATE TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA INTERMEDIATE TO ROLE IOT_TRANSFORMER;

GRANT USAGE ON SCHEMA MARTS TO ROLE IOT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA MARTS TO ROLE IOT_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA MARTS TO ROLE IOT_TRANSFORMER;
GRANT CREATE ICEBERG TABLE ON SCHEMA MARTS TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MARTS TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARTS TO ROLE IOT_TRANSFORMER;

GRANT USAGE ON SCHEMA MONITORING TO ROLE IOT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA MONITORING TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MONITORING TO ROLE IOT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MONITORING TO ROLE IOT_TRANSFORMER;

-- IOT_READER: read-only on MARTS
GRANT USAGE ON SCHEMA MARTS TO ROLE IOT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS TO ROLE IOT_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE IOT_READER;

-- Grant roles to SYSADMIN (best practice: role hierarchy)
GRANT ROLE IOT_LOADER TO ROLE SYSADMIN;
GRANT ROLE IOT_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE IOT_READER TO ROLE SYSADMIN;

-- =====================
-- 6. VERIFICATION
-- =====================
SHOW SCHEMAS IN DATABASE IOT_PIPELINE;
SHOW ROLES LIKE 'IOT_%';
SHOW WAREHOUSES LIKE 'IOT_%';
